---
name: Posy-Plugin-CgiFile
version: 0.01
author:
  - Kathryn Andersen
abstract: Posy plugin to enable drop-in use of CGI scripts inside Posy.
license: perl
requires:
  Posy: 0.97
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::CgiFile:
    file: lib/Posy/Plugin/CgiFile.pm
    version: 0.01
generated_by: Module::Build version 0.2611
